name: build-binaries

on:
  push:
    branches: [ main, master ]
    tags: [ "v*" ]

permissions:
  contents: write  # needed for release upload

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            py: "3.11"
            arch: x64
            artifact: midi2furnace-win-x64
          - os: macos-latest
            py: "3.11"
            arch: arm64   # GitHub macOS runners are Apple Silicon
            artifact: midi2furnace-mac-arm64
          - os: ubuntu-22.04
            py: "3.11"
            arch: x64
            artifact: midi2furnace-linux-x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}
          cache: "pip"

      - name: Install system deps (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgl1 libglib2.0-0 libasound2 \
            libx11-6 libxext6 libxrender1 libxcursor1 libxrandr2 libxi6 libxxf86vm1 zip

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build (PyInstaller onedir)
        run: |
          python -c "import os; print('CWD:', os.getcwd())"
          pyinstaller --noconfirm --workpath .pyibld build/midi2furnace.spec

      # Windows-only: remove extra root exe if PyInstaller drops one
      - name: Cleanup extra root exe (Windows)
        if
